spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_usstnews?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password:
server:
  port: 8888
