spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_usstnews?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: root
server:
  port: 6666
